
@Restaurants.API_HostAddress = https://localhost:7027

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

Post {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json


{
  "Name":"test",
  "Description":"tttttttt",
  "Category":"ddd"
}

###
